#!/bin/sh

# Install this hook in git/hooks to run before each git commit call
# I suggest doing this as a symlink to keep changes synced via git.

set -eu
exec < /dev/tty


offer_death() {
  read -r -p "Commit changes anyways? [y/N] " response
  case "$response" in
      [yY][eE][sS]|[yY])
        echo "Ok lolz sure."
        ;;
      *)
        echo "No shame."
        exit 1
        ;;
  esac
}


offer_reformatting() {
  blue --diff src
  read -r -p "Apply reformatting? [y/N] " response
  case "$response" in
      [yY][eE][sS]|[yY])
        blue src
        echo "Fixed formatting automatically. Now try again!"
        exit 1
        ;;
      *)
        offer_death
        ;;
  esac
}


offer_fix_imports() {
  isort --profile black --line-length=79 --diff src
  read -r -p "Apply imports reformatting? [y/N] " response
  case "$response" in
      [yY][eE][sS]|[yY])
        isort --profile black --line-length=79 src
        echo "Fixed imports formatting automatically. Now try again!"
        exit 1
        ;;
      *)
        offer_death
        ;;
  esac
}


echo "\nRunning pytest..."
pytest src || offer_death

echo "\nRunning mypy..."
mypy --warn-unreachable --no-implicit-reexport --strict-equality src || offer_death

echo "\nRunning pyflakes..."
pyflakes src || offer_death

echo "\nRunning blue..."
blue --check src || offer_reformatting

echo "\nRunning isort..."
isort --profile black --line-length=79 --check src || offer_fix_imports