#!/bin/sh

# Install this hook in git/hooks to run before each git push call
# I suggest doing this as a symlink to keep changes synced via git.

set -eu
exec < /dev/tty


offer_death() {
  read -r -p "Commit changes anyways? [y/N] " response
  case "$response" in
      [yY][eE][sS]|[yY])
        echo "Ok lolz sure."
        ;;
      *)
        echo "No shame."
        exit 1
        ;;
  esac
}

echo "\nRunning mypy --strict..."
mypy --strict src || offer_death