name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --workspace --verbose

  warn:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
    - uses: actions/checkout@v3
    - name: Build with -D warnings
      run: cargo build --workspace --verbose

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --workspace --verbose

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run linters
      run: cargo clippy --workspace
  
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run fmt
      run: cargo fmt --check --all
